import { Project, Alert, Category, OnboardingSlide } from '../types';
import images from '../assets/images';

export const categories: Category[] = [
  'Saúde',
  'Educação',
  'Segurança',
  'Trabalho',
  'Meio Ambiente',
  'Economia',
  'Direitos Humanos',
  'Tecnologia',
];

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Ampliação do Sistema Único de Saúde',
    number: 'PL 1234/2025',
    summary: 'Propõe a ampliação do atendimento do SUS com novas unidades e investimentos em tecnologia médica.',
    category: 'Saúde',
    status: 'Em tramitação',
    date: '2025-10-15',
    authorId: '1',
    authorName: 'Dep. Maria Silva',
    currentStage: 'Comissão de Saúde',
    progress: 45,
    isFavorite: false,
  },
  {
    id: '2',
    title: 'Reforma do Ensino Médio',
    number: 'PL 5678/2025',
    summary: 'Estabelece novas diretrizes para o ensino médio com foco em tecnologia e desenvolvimento de competências.',
    category: 'Educação',
    status: 'Em tramitação',
    date: '2025-10-10',
    authorId: '2',
    authorName: 'Sen. João Santos',
    currentStage: 'Comissão de Educação',
    progress: 60,
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Programa Nacional de Segurança Urbana',
    number: 'PL 9012/2025',
    summary: 'Cria programa de integração entre polícias estaduais e municipais para combate à criminalidade.',
    category: 'Segurança',
    status: 'Em análise',
    date: '2025-10-05',
    authorId: '3',
    authorName: 'Dep. Carlos Oliveira',
    currentStage: 'Comissão de Segurança Pública',
    progress: 30,
    isFavorite: false,
  },
  {
    id: '4',
    title: 'Modernização da CLT',
    number: 'PL 3456/2025',
    summary: 'Atualiza legislação trabalhista com foco em trabalho remoto e economia digital.',
    category: 'Trabalho',
    status: 'Em tramitação',
    date: '2025-09-28',
    authorId: '4',
    authorName: 'Sen. Ana Paula',
    currentStage: 'Comissão de Trabalho',
    progress: 50,
    isFavorite: false,
  },
  {
    id: '5',
    title: 'Proteção de Áreas Verdes Urbanas',
    number: 'PL 7890/2025',
    summary: 'Estabelece normas para preservação de áreas verdes em centros urbanos e incentivo ao reflorestamento.',
    category: 'Meio Ambiente',
    status: 'Em tramitação',
    date: '2025-09-20',
    authorId: '5',
    authorName: 'Dep. Roberto Lima',
    currentStage: 'Comissão de Meio Ambiente',
    progress: 70,
    isFavorite: true,
  },
  {
    id: '6',
    title: 'Reforma Tributária Simplificada',
    number: 'PL 2468/2025',
    summary: 'Propõe simplificação do sistema tributário brasileiro com redução de impostos para pequenas empresas.',
    category: 'Economia',
    status: 'Em tramitação',
    date: '2025-09-15',
    authorId: '6',
    authorName: 'Sen. Fernando Costa',
    currentStage: 'Comissão de Economia',
    progress: 40,
    isFavorite: false,
  },
  {
    id: '7',
    title: 'Lei de Proteção de Dados do Cidadão',
    number: 'PL 1357/2025',
    summary: 'Amplia direitos de proteção de dados pessoais e estabelece penalidades para vazamentos.',
    category: 'Tecnologia',
    status: 'Aprovado',
    date: '2025-08-30',
    authorId: '7',
    authorName: 'Dep. Paula Rodrigues',
    currentStage: 'Sanção Presidencial',
    progress: 95,
    isFavorite: true,
  },
  {
    id: '8',
    title: 'Programa de Combate à Violência Doméstica',
    number: 'PL 9876/2025',
    summary: 'Cria rede de apoio e proteção para vítimas de violência doméstica com medidas preventivas.',
    category: 'Direitos Humanos',
    status: 'Em tramitação',
    date: '2025-08-25',
    authorId: '8',
    authorName: 'Dep. Mariana Alves',
    currentStage: 'Comissão de Direitos Humanos',
    progress: 55,
    isFavorite: false,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    title: 'Atualização no PL 5678/2025',
    message: 'O projeto sobre Reforma do Ensino Médio avançou para a próxima fase.',
    type: 'update',
    date: '2025-10-20T10:30:00',
    isRead: false,
    projectId: '2',
  },
  {
    id: '2',
    title: 'Novo projeto de interesse',
    message: 'Foi criado um novo projeto na categoria Saúde que pode ser do seu interesse.',
    type: 'info',
    date: '2025-10-19T14:15:00',
    isRead: false,
    projectId: '1',
  },
  {
    id: '3',
    title: 'Projeto aprovado!',
    message: 'O PL 1357/2025 sobre Proteção de Dados foi aprovado e segue para sanção.',
    type: 'success',
    date: '2025-10-18T09:00:00',
    isRead: true,
    projectId: '7',
  },
  {
    id: '4',
    title: 'Votação importante',
    message: 'O projeto sobre Meio Ambiente será votado amanhã na Comissão.',
    type: 'info',
    date: '2025-10-17T16:45:00',
    isRead: true,
    projectId: '5',
  },
];

export const onboardingSlides: OnboardingSlide[] = [
  {
    id: 1,
    title: 'Bem-Vindo ao Veritas!',
    subtitle: 'Acompanhe Projetos de Lei',
    description: 'Entenda o impacto de projetos que afetam sua vida e da sociedade com linguagem simples e clara.',
    illustration: '👥',
    illustrationImage: images.onboarding1,
  },
  {
    id: 2,
    title: 'Fique por Dentro',
    subtitle: 'Receba Alertas Personalizados',
    description: 'Seja notificado quando houver novidades em projetos sobre temas que importam para você.',
    illustration: '🔔',
    illustrationImage: images.onboarding2,
  },
  {
    id: 3,
    title: 'Exerça sua Cidadania',
    subtitle: 'Participe Ativamente',
    description: 'Acompanhe a tramitação, favorite projetos e exerça sua cidadania de forma consciente.',
    illustration: '🏛️',
    illustrationImage: images.onboarding3,
  },
];
